<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <LangVersion>latest</LangVersion>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <IsPackable>false</IsPackable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.0.1" />
        <PackageReference Include="NUnit" Version="4.4.0" />
        <PackageReference Include="NUnit3TestAdapter" Version="6.1.0" />
        <PackageReference Include="NUnit.Analyzers" Version="4.11.2">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="coverlet.collector" Version="6.0.4">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\CGLibrary\CGLibrary.csproj" />
    </ItemGroup>

    <ItemGroup>
        <Compile Remove="_Store\**" />
        <Compile Remove="BentlyOttmannTests.cs" />
        <Compile Remove="Double-Tests\ConvexPolygonIntersectionTests.cs" />
        <Compile Remove="Double-Tests\SegmentCrossTests.cs" />
        <Compile Remove="Double-Tests\VectorsTests.cs" />
        <Compile Remove="SharedTests\AffineBasisTest.cs" />
        <Compile Remove="SharedTests\MatrixTests.cs" />
        <Compile Remove="SharedTests\LinearBasisTests.cs" />
        <Compile Remove="SharedTests\VectorTests.cs" />
    </ItemGroup>

    <ItemGroup>
        <EmbeddedResource Remove="_Store\**" />
    </ItemGroup>

    <ItemGroup>
        <None Remove="_Store\**" />
    </ItemGroup>
    
    <ItemGroup>
        <Reference Include="DoubleDouble">
            <HintPath>..\DoubleDouble.dll</HintPath>
        </Reference>
        <Reference Include="Rationals">
            <HintPath>..\Rationals.dll</HintPath>
        </Reference>
    </ItemGroup>
    
    <ItemGroup>
      <Folder Include="ToolsForTests\ConvexPolytopes\" />
    </ItemGroup>

</Project>
