<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <LangVersion>13</LangVersion>
        <Nullable>enable</Nullable>

        <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    </PropertyGroup>

    <ItemGroup>
        <InternalsVisibleTo Include="Tests"/>
    </ItemGroup>

    <ItemGroup>
        <Compile Remove="Class1.cs"/>
        <Compile Remove="_\**"/>
        <Compile Include="Basics\AffineBasis.cs"/>
        <Compile Include="Basics\AffineBasisMutable.cs"/>
        <Compile Include="Basics\CauchyMatrix.cs"/>
        <Compile Include="Basics\HyperPlane.cs"/>
        <Compile Include="Basics\LinearBasis.cs"/>
        <Compile Include="Basics\LinearBasisMutable.cs"/>
        <Compile Include="Basics\Matrix.cs" />
        <Compile Include="Basics\Vector.cs"/>
        <Compile Include="Basics\Vector2D.cs"/>
        <Compile Include="Algorithms\ConvexHull2D\Convexification.cs"/>
        <Compile Include="Algorithms\Polyhedra\GiftWrapping\BaseSubCP.cs"/>
        <Compile Include="Algorithms\Polyhedra\GiftWrapping\GiftWrapping.cs"/>
        <Compile Include="Algorithms\Polyhedra\GiftWrapping\SubPolytop.cs"/>
        <Compile Include="Algorithms\Polyhedra\GiftWrapping\SubSimplex.cs"/>
        <Compile Include="Algorithms\Polyhedra\GiftWrapping\SubTwoDimensionalEdge.cs"/>
        <Compile Include="Algorithms\Polyhedra\GiftWrapping\SubPoint2D.cs"/>
        <Compile Include="Algorithms\Polyhedra\GiftWrapping\SubPoint.cs"/>
        <Compile Include="Algorithms\Polyhedra\GiftWrapping\SubTwoDimensional.cs"/>
        <Compile Include="Algorithms\Polyhedra\GiftWrapping\SubZeroDimensional.cs"/>
        <Compile Include="Algorithms\Polyhedra\HrepToFLrep.cs"/>
        <Compile Include="Algorithms\Polyhedra\MinkowskiSum.cs"/>
        <Compile Include="Algorithms\Polyhedra\MinkowskiDiff.cs"/>
        <Compile Include="Geometry2D\Line2D.cs"/>
        <Compile Include="GlobalUsings.cs"/>
        <Compile Include="LinearMath\FourierMotzkin.cs"/>
        <Compile Include="LinearMath\GaussSLE.cs"/>
        <Compile Include="LinearMath\Decomposition.cs" />
        <Compile Include="LinearMath\SimplexMethod.cs"/>
        <Compile Include="Geometry2D\Polygons\BasicPolygon.cs"/>
        <Compile Include="Geometry2D\Polygons\ConvexPolygons\ConvexPolygon.cs"/>
        <Compile Include="Geometry2D\Polygons\ConvexPolygons\GammaPair.cs"/>
        <Compile Include="Geometry2D\Polygons\ConvexPolygons\Intersection.cs"/>
        <Compile Include="Geometry2D\Polygons\ConvexPolygons\SupportFunction.cs"/>
        <Compile Include="Geometry2D\Polygons\PolygonTools.cs"/>
        <Compile Include="Geometry2D\Polygons\Polyline.cs"/>
        <Compile Include="GeometryND\Polyhedra\ConvexPolytop.cs"/>
        <Compile Include="GeometryND\Polyhedra\FaceLattice.cs"/>
        <Compile Include="Geometry2D\Segments\Segment.cs"/>
        <Compile Include="Geometry2D\Segments\SegmentPair.cs"/>
        <Compile Include="Toolkit\Combinations.cs"/>
        <Compile Include="Toolkit\Extensions.cs"/>
        <Compile Include="Toolkit\Hashes.cs"/>
        <Compile Include="Toolkit\ParamReader.cs"/>
        <Compile Include="Toolkit\ParamWriter.cs"/>
        <Compile Include="Toolkit\RandomLC.cs"/>
        <Compile Include="Toolkit\Tools.cs"/>
    </ItemGroup>

    <ItemGroup>
        <EmbeddedResource Remove="_\**"/>
    </ItemGroup>

    <ItemGroup>
        <None Remove="_\**"/>
    </ItemGroup>

    <ItemGroup>
        <Reference Include="AVLUtils">
            <HintPath>..\..\AVLUtils\AVLUtils\bin\Release\net8.0\AVLUtils.dll</HintPath>
        </Reference>
    </ItemGroup>

    <ItemGroup>
        <Content Include="Geometry2D\Segments\Bentley-Ottmann\BentleyOttmann.svg"/>
        <Content Include="Geometry2D\Segments\Bentley-Ottmann\BentleyOttmannBasic.cs_old"/>
        <Content Include="Geometry2D\Segments\Bentley-Ottmann\BentleyOttmannBasic.cs_store"/>
        <Content Include="Geometry2D\Segments\Bentley-Ottmann\BentleyOttmannRealizations.cs_store"/>
        <Content Include="Geometry2D\Segments\Bentley-Ottmann\Event.cs_store"/>
        <Content Include="Geometry2D\Segments\Bentley-Ottmann\EventQueue.cs_store"/>
        <Content Include="Geometry2D\Segments\Bentley-Ottmann\InnerSegment.cs_store"/>
        <Content Include="Geometry2D\Segments\Bentley-Ottmann\SegmentGroup.cs_store"/>
        <Content Include="Geometry2D\Segments\Bentley-Ottmann\SweepLineSegmentComparer.cs_store"/>
        <Content Include="Geometry2D\Segments\Bentley-Ottmann\YStructure.cs_store"/>
    </ItemGroup>


</Project>
